### ISSUE TITLE
Ansible: Change Inventory Structure

### ISSUE THREAD

**Issue by mkdeegan** [Azure/sap-hana#492]
**Is your feature request related to a problem? Please describe.**
Currently there is no way for multiple inventories to aggregate.
Inventories should be keyed off an identifier (SID) and an Application Layer.
A structure like the one shown below allows Ansilble to execute against groups, and the members of the Groups to have a fact set to Identify the operational _tier_
Inventories should be output in a YAML format.

**Describe the solution you'd like**
A YAML formate file with servers grouped by SID and Tier
```
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                                  HOSTS                                     |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# +------------------------------------4--------------------------------------*/
Z00_HDB:
    hosts:
        z00hdb00:
            ansible_host: z00hdb00.scus.azure.mysapbasis.com
    vars:
        tier: hdb
        # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ansible@pub0scusdeploy00.southcentralus.cloudapp.azure.com"'
Z00_SCS:
    hosts:
        z00scs00:
            ansible_host: z00scs00.scus.azure.mysapbasis.com
    vars:
        tier: scs
        # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ansible@pub0scusdeploy00.southcentralus.cloudapp.azure.com"'
Z00_PAS:
    hosts:
        z00app00:
            ansible_host: z00app00.scus.azure.mysapbasis.com
    vars:
        tier: pas
        # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ansible@pub0scusdeploy00.southcentralus.cloudapp.azure.com"'
Z00_APP:
    hosts:
        z00app01:
            ansible_host: z00app01.scus.azure.mysapbasis.com
        z00app02:
            ansible_host: z00app02.scus.azure.mysapbasis.com
    vars:
        tier: app
        # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ansible@pub0scusdeploy00.southcentralus.cloudapp.azure.com"'
Z00_WEB:
    hosts:
        z00web00:
            ansible_host: z00web00.scus.azure.mysapbasis.com
    vars:
        tier: web
...
```

The commented out _ansible_ssh_common_args_ demonstrates how to execute sensible through an intermediary Jumpbox, which is not part of our current design.
**Additional context**
This allow for predictable execution based on input parameters and targeted Tier execution.
